using System;
using System.Reflection;
using System.Runtime.InteropServices;

// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: CLSCompliantAttribute(true)]
[assembly: AssemblyTitleAttribute("Apache NMS Connection Pooling Class Library")]
[assembly: AssemblyDescriptionAttribute("Apache NMS Connection Pooling Class Library (.Net Messaging Library Implementation): An implementation of the NMS API for Pooling NMS Connection Resources")]
[assembly: AssemblyConfigurationAttribute("SNAPSHOT")]
[assembly: AssemblyCompanyAttribute("http://activemq.apache.org/nms")]
[assembly: AssemblyProductAttribute("Apache NMS Connection Pooling Class Library")]
[assembly: AssemblyCopyrightAttribute("Copyright (C) 2005-2012 Apache Software Foundation")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyCultureAttribute("")]
[assembly: AssemblyVersionAttribute("1.6.0.2562")]
[assembly: AssemblyInformationalVersionAttribute("1.6.0")]

